apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "team-1-podtato-datadog"
  description: "team-1-podtato-datadog"
  tags:
    - sx-cnp-oss
    - template
    - kargo
    - metalstack
    - kubex
  links:
    - url: http://team-1-podtato-head-test.demo-ddog.kubrix.cloud/
      title: Test Instance of sx-cnp-oss-jokl-app
      icon: web
  annotations:
    github.com/project-slug: kubriX-demo/team-1-podtato-head
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=podtato-datadog'
    argocd/app-namespace: adn-team-1
    argocd/app-name: podtato-datadog
    backstage.io/techdocs-ref: dir:.
    kargo-project: "https://kargo.demo-ddog.kubrix.cloud/project/sx-cnp-oss-jokl-app-kargo-project"
    datadoghq.com/dashboard-url: "https://p.datadoghq.eu/sb/d7b204ed-f38f-11ef-9296-be0cc9f2c79c-f9ab3823e95622bf1fd15a84064d187f"
    datadoghq.com/graph-token: "7c0d16066197b59d4d7afca821c6122954a43819072fbe2a8f43df263c1d8586"
spec:
  type: service
  lifecycle: test
  owner: "sx-cnp-oss"
  system: jokl-app
  dependsOn:
    - resource:argocd
    - resource:kubecost
    - resource:grafana
    - resource:metalstack
    - resource:loki
    - resource:kyverno
    - resource:tempo
    - resource:backstage
