ingressSuffix: test.demo-ddog.kubrix.cloud

ingress:
  className: nginx
  annotations:
    dns.gardener.cloud/class: garden
    dns.gardener.cloud/dnsnames: team-1-podtato-head-{{ .Values.ingressSuffix }}
    dns.gardener.cloud/ttl: "180"
    # another comment from upstream should go to downstream
  hosts:
    - host: team-1-podtato-head-{{ .Values.ingressSuffix }}
      paths:
        - path: /
          pathType: ImplementationSpecific
